version: '3.4'

services:
  toiproject1:
    image: toiproject1
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - mosquitto
  mosquitto:
    image: eclipse-mosquitto:1.6
    ports:
      - 1883:1883
      - 9001:9001